//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JeuDontOnEstLeHeros.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Avatar
    {
        public decimal Id { get; set; }
        public string Surnom { get; set; }
        public bool Sexe { get; set; }
        public decimal EspeceId { get; set; }
    
        public virtual Espece Espece { get; set; }
    }
}
